name: "CI without cache"

on:
  push:
    branches:
      - main

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker ps
        run: docker ps
      